name: prototype_ss
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  http: ^0.13.3
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  firebase_auth: ^4.4.3
  uuid: ^4.4.0
  firebase_storage: ^11.7.7
  provider: ^6.0.2
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banners/banner1.jpg
    - assets/images/banners/banner2.jpg
    - assets/images/banners/banner3.jpg

