// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmG-NGkD3FhJQ6JBW6cCFVqogjq9cONTM',
    appId: '1:577971703836:web:4a05123a2d3d31da020fd9',
    messagingSenderId: '577971703836',
    projectId: 'ss-project-final',
    authDomain: 'ss-project-final.firebaseapp.com',
    storageBucket: 'ss-project-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJYzy416quOdblak35h31pIiKOFPZSUc',
    appId: '1:577971703836:android:cc7ac6d9cfa54fdd020fd9',
    messagingSenderId: '577971703836',
    projectId: 'ss-project-final',
    storageBucket: 'ss-project-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiVfQjiBjGKfwzUHgQSbyrpDjYeVe6CQ',
    appId: '1:577971703836:ios:dfa3d4614e7b1efb020fd9',
    messagingSenderId: '577971703836',
    projectId: 'ss-project-final',
    storageBucket: 'ss-project-final.appspot.com',
    iosBundleId: 'com.example.prototypeSs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiVfQjiBjGKfwzUHgQSbyrpDjYeVe6CQ',
    appId: '1:577971703836:ios:dfa3d4614e7b1efb020fd9',
    messagingSenderId: '577971703836',
    projectId: 'ss-project-final',
    storageBucket: 'ss-project-final.appspot.com',
    iosBundleId: 'com.example.prototypeSs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmG-NGkD3FhJQ6JBW6cCFVqogjq9cONTM',
    appId: '1:577971703836:web:3cc887ba310b2ee0020fd9',
    messagingSenderId: '577971703836',
    projectId: 'ss-project-final',
    authDomain: 'ss-project-final.firebaseapp.com',
    storageBucket: 'ss-project-final.appspot.com',
  );

}